name: audiotagger
description: Library to read and write ID3 tags to MP3 files. You can get data as Map object or Tag object.
version: 2.2.1
homepage: https://github.com/Samurai016/Audiotagger

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nicolorebaioli.audiotagger
        pluginClass: AudiotaggerPlugin